/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

import Code.DBconnect;
import com.sun.glass.events.KeyEvent;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.HeadlessException;
import java.awt.Toolkit;
import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author Thakshara Dhananjaya
 */
public class Loging_Frame extends javax.swing.JFrame {

    int mouseX;
    int mouseY;

    // Var for conrol DB 
    Connection conn = null;
    PreparedStatement Pstatement = null;
    ResultSet resualt = null;

    /**
     * Creates new form Loging_Frame
     */
    public Loging_Frame() {
        initComponents();


        /*String result="";
         try {
         Process p = Runtime.getRuntime().exec("wmic baseboard get serialnumber");
         BufferedReader inn = new BufferedReader(new InputStreamReader(p.getInputStream()));

         String line="";
        
         while ((line = inn.readLine()) != null)
         {
         result += line;
         }
         result=result.replace("SerialNumber  ", "");
         result=result.replace(" ", "");
         } catch (Exception e) {
        
         }
         if(!"PGBKCC5WV46MAY".equals(result))
         {
         JOptionPane.showMessageDialog(null, "Not license for shop managemant system run on this computer !", "Shop Management System",JOptionPane.WARNING_MESSAGE);
         System.exit(0);
         }
         */
        login_uname.requestFocus();
        //conect DB 
        conn = DBconnect.connect();

        //Frame open in center screen
        Toolkit toolkit = getToolkit();
        Dimension size = toolkit.getScreenSize();
        setLocation(size.width / 2 - getWidth() / 2, size.height / 2 - getHeight() / 2);

        try {
            setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/Images/SW_Logo.png")));
        } catch (Exception e) {

        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        loging_close_btn = new javax.swing.JLabel();
        login_uname = new rojeru_san.RSMTextFull();
        login_pswd = new rojeru_san.RSMPassView();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        signin_btn = new rojeru_san.RSButtonRiple();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Shop Management System");
        setName("Loging_frame"); // NOI18N
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(675, 450));
        setResizable(false);
        setSize(new java.awt.Dimension(660, 450));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Sign_in.png"))); // NOI18N
        jLabel3.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jLabel3MouseDragged(evt);
            }
        });
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel3MousePressed(evt);
            }
        });
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, 0, 330, 450);

        jPanel1.setBackground(new java.awt.Color(45, 137, 239));
        jPanel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel1MouseDragged(evt);
            }
        });
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel1MousePressed(evt);
            }
        });
        jPanel1.setLayout(null);

        loging_close_btn.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        loging_close_btn.setForeground(new java.awt.Color(204, 204, 204));
        loging_close_btn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        loging_close_btn.setText("X");
        loging_close_btn.setToolTipText("Close");
        loging_close_btn.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                loging_close_btnMouseMoved(evt);
            }
        });
        loging_close_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loging_close_btnMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                loging_close_btnMouseExited(evt);
            }
        });
        jPanel1.add(loging_close_btn);
        loging_close_btn.setBounds(329, 1, 18, 18);

        login_uname.setForeground(new java.awt.Color(0, 102, 102));
        login_uname.setPlaceholder("");
        login_uname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                login_unameKeyPressed(evt);
            }
        });
        jPanel1.add(login_uname);
        login_uname.setBounds(30, 130, 250, 42);

        login_pswd.setForeground(new java.awt.Color(0, 102, 102));
        login_pswd.setPlaceholder("");
        login_pswd.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                login_pswdKeyPressed(evt);
            }
        });
        jPanel1.add(login_pswd);
        login_pswd.setBounds(30, 220, 250, 42);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("User Name");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(30, 100, 150, 25);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Password");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(30, 190, 120, 25);

        signin_btn.setBackground(new java.awt.Color(0, 173, 51));
        signin_btn.setText("Sign in");
        signin_btn.setToolTipText("Click to here sign in");
        signin_btn.setColorHover(new java.awt.Color(28, 231, 30));
        signin_btn.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        signin_btn.setFocusable(false);
        signin_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signin_btnActionPerformed(evt);
            }
        });
        jPanel1.add(signin_btn);
        signin_btn.setBounds(100, 300, 110, 30);

        jLabel4.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 10)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Develop by Thakshara Dhananjaya");
        jLabel4.setToolTipText("Contact: 077 659 1828");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(176, 431, 170, 20);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Welcome!");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(29, 29, 110, 25);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Sign in to your account");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(30, 54, 130, 15);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(328, 0, 357, 450);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jPanel1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - mouseX, y - mouseY);
    }//GEN-LAST:event_jPanel1MouseDragged

    private void jPanel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MousePressed
        // Get mouse location for Window move
        mouseX = evt.getX();
        mouseY = evt.getY();
    }//GEN-LAST:event_jPanel1MousePressed

    private void loging_close_btnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loging_close_btnMouseClicked
        System.exit(0);
    }//GEN-LAST:event_loging_close_btnMouseClicked

    private void loging_close_btnMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loging_close_btnMouseMoved
        loging_close_btn.setForeground(Color.red);//Mouse hover color
    }//GEN-LAST:event_loging_close_btnMouseMoved

    private void loging_close_btnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loging_close_btnMouseExited
        loging_close_btn.setForeground(new Color(204, 204, 204)); // Defualt color to mouse ext
    }//GEN-LAST:event_loging_close_btnMouseExited

    private void login_pswdKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_login_pswdKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            login();
        }
    }//GEN-LAST:event_login_pswdKeyPressed

    private void login_unameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_login_unameKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            login_pswd.requestFocus();
        }
    }//GEN-LAST:event_login_unameKeyPressed

    private void signin_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signin_btnActionPerformed
        String cmd = "\"C:\\Program Files\\MySQL\\MySQL Server 5.7\\bin\\mysqldump\" -uroot -pafs@sms aanya_fashion > E:\\Auto_Backup\\automatic_backup.sql";

        try {
            Process runtimeProcess = Runtime.getRuntime().exec(new String[]{"cmd.exe", "/c", cmd});
            JOptionPane.showMessageDialog(null, "Backup Complete", "Shop Management System", JOptionPane.INFORMATION_MESSAGE);
        } catch (IOException | HeadlessException ex) {
            JOptionPane.showMessageDialog(null, "Backup Failure", "Shop Management System", JOptionPane.WARNING_MESSAGE);
        }
        login();
    }//GEN-LAST:event_signin_btnActionPerformed

    private void jLabel3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MousePressed
        // Get mouse location for Window move
        mouseX = evt.getX();
        mouseY = evt.getY();
    }//GEN-LAST:event_jLabel3MousePressed

    private void jLabel3MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - mouseX, y - mouseY);
    }//GEN-LAST:event_jLabel3MouseDragged

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        try {
            String sqlQuery = "SELECT `Item ID`,`Quantity` FROM `billitem` WHERE `Complete` = 1";
            Pstatement = conn.prepareStatement(sqlQuery);
            resualt = Pstatement.executeQuery();      

            while (resualt.next()) {
                int ItemID = 0;
                int Qty = 0;
                ItemID = resualt.getInt("Item ID");
                Qty = resualt.getInt("Quantity");

                if (Qty>0) {
                    sqlQuery = "UPDATE `item` SET `Quantity`= `item`.`Quantity` + "+Qty+" WHERE `Item ID` = '" + ItemID + "' ";
                    System.out.println(sqlQuery);
                    Pstatement = conn.prepareStatement(sqlQuery);
                    Pstatement.execute();
                }
            }
            
            sqlQuery = "SELECT `Bill ID` FROM `billitem` WHERE `Complete` = 1";
            Pstatement = conn.prepareStatement(sqlQuery);
            resualt = Pstatement.executeQuery();

            while (resualt.next()) {
                String BillID = "";
                BillID = resualt.getString("Bill ID");
                if (!BillID.equals("")) {
                    sqlQuery = "DELETE FROM `billitem` WHERE `Bill ID` = '" + BillID + "'";
                    Pstatement = conn.prepareStatement(sqlQuery);
                    Pstatement.execute();
                }
            }

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e, "Shop Management System", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_formWindowOpened

    public void login() {
        String uname = login_uname.getText();
        String pswd = String.valueOf(login_pswd.getPassword());

        if (uname.equals("") && pswd.equals("")) {
            JOptionPane.showMessageDialog(null, "Pleas enter User Name and Password", "Shop Management System", JOptionPane.WARNING_MESSAGE);
            login_pswd.setText("");
        } else if (uname.equals("")) {
            JOptionPane.showMessageDialog(null, "Pleas enter User Name", "Shop Management System", JOptionPane.WARNING_MESSAGE);
        } else if (pswd.equals("")) {
            JOptionPane.showMessageDialog(null, "Pleas enter Password", "Shop Management System", JOptionPane.WARNING_MESSAGE);
            login_pswd.setText("");
        } else {
            String us_nm = "";
            try {
                String sqlload = "SELECT `User Name` From `user_acct` WHERE `User Name` = '" + uname + "'";
                Pstatement = conn.prepareStatement(sqlload);
                resualt = Pstatement.executeQuery();

                while (resualt.next()) {
                    us_nm = resualt.getString("User Name");
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e, "Shop Management System", JOptionPane.WARNING_MESSAGE);
            }
            if ("".equals(us_nm)) {
                JOptionPane.showMessageDialog(null, "User Name or Password doesn't match", "Shop Management System", JOptionPane.WARNING_MESSAGE);
                login_pswd.setText("");
            } else {
                String pass = "";
                String caid = "";
                try {
                    String sqlload = "SELECT `Password`, `CaID` From `user_acct` WHERE `User Name` = '" + uname + "'";
                    Pstatement = conn.prepareStatement(sqlload);
                    resualt = Pstatement.executeQuery();

                    while (resualt.next()) {
                        pass = resualt.getString("Password");
                        caid = resualt.getString("CaID");
                    }
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, e, "Shop Management System", JOptionPane.WARNING_MESSAGE);
                }
                if (pswd.equals(pass)) {
                    ArrayList<String> s = new ArrayList<>();
                    s.add(us_nm);
                    s.add(caid);
                    new Home(s).setVisible(true);
                    this.dispose();
                } else {
                    JOptionPane.showMessageDialog(null, "User Name or Password doesn't match", "Shop Management System", JOptionPane.WARNING_MESSAGE);
                    login_pswd.setText("");
                }
            }
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Window".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Loging_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Loging_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Loging_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Loging_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Loging_Frame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private rojeru_san.RSMPassView login_pswd;
    private rojeru_san.RSMTextFull login_uname;
    private javax.swing.JLabel loging_close_btn;
    private rojeru_san.RSButtonRiple signin_btn;
    // End of variables declaration//GEN-END:variables

}
